[package]
name = "rust_cmr"
path = "src/queries.rs"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
reqwest = "0.12"
serde_json = "1.0"
url = "2.5"
tokio = { version = "1", features = ["full"] }